add lang parameter
Emvista/PSS-Documentation pull request #49
Opened 2020-08-19 08:48 UTC by jeanemvista

2020-08-19 09:11 UTC, NguyenAntoine requested changes

2020-08-19 09:11 UTC, NguyenAntoine commented on pss/README_HIGHLIGHTER.md
> +    "namedentities" : [ {
```suggestion
    "namedEntities" : [ {
```

2020-08-19 09:11 UTC, NguyenAntoine commented on pss/README_ANONYMISATION.md
> +    "namedentities" : [ {
```suggestion
    "namedEntities" : [ {
```

2020-08-19 09:15 UTC, NguyenAntoine commented on pss/README_PARSER.md
>  * Header : Content-Type: application/json
L'image de parser n'existe pas

2020-08-19 09:47 UTC, NguyenAntoine commented on pss/README_PARSER.md
>  * Header : Content-Type: application/json
#32 issue déjà soumise

2020-08-19 09:48 UTC, NguyenAntoine approved these changes

2020-08-19 13:56 UTC, thibaud-sanchez approved these changes
Pourquoi avoir supprimé tous les outputs ?

2020-08-19 14:02 UTC, NguyenAntoine commented
> Pourquoi avoir supprimé tous les outputs ?

Il les a déplacé en haut

2020-08-24 09:03 UTC, MMel1ssa approved these changes

2020-08-24 09:08 UTC, merged